# Generated by Django 4.1.1 on 2022-09-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0004_alter_staff_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=1000, verbose_name='Приоритет')),
                ('departments', models.ManyToManyField(blank=True, related_name='sidebar', to='staff.department', verbose_name='Подразделения')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
