# Generated by Django 4.1.1 on 2022-09-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'verbose_name': 'настройки', 'verbose_name_plural': 'настройки'},
        ),
        migrations.RemoveField(
            model_name='sidebar',
            name='ordering',
        ),
    ]
