# Generated by Django 4.1.1 on 2022-09-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_options'),
        ('core', '0002_alter_sidebar_options_remove_sidebar_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar', models.ManyToManyField(blank=True, related_name='sidebar', to='staff.department', verbose_name='Подразделения')),
            ],
            options={
                'verbose_name': 'настройки',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.DeleteModel(
            name='Sidebar',
        ),
    ]
