# Generated by Django 4.1.1 on 2022-09-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'подразделение', 'verbose_name_plural': 'подразделения'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-priority',), 'verbose_name': 'должность', 'verbose_name_plural': 'должности'},
        ),
        migrations.AlterModelOptions(
            name='posttype',
            options={'ordering': ('-priority',), 'verbose_name': 'тип должности', 'verbose_name_plural': 'типы должностей'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AddField(
            model_name='staff',
            name='priority',
            field=models.PositiveIntegerField(default=1000, verbose_name='Приоритет'),
        ),
    ]
