# Generated by Django 4.1.1 on 2022-09-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_department_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('parent__title', 'title'), 'verbose_name': 'подразделение', 'verbose_name_plural': 'подразделения'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-post_type__priority', '-priority'), 'verbose_name': 'должность', 'verbose_name_plural': 'должности'},
        ),
        migrations.AddField(
            model_name='department',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='staff',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
